# Generated by Django 5.2.7 on 2026-07-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(
                choices=[
                    ("NOTE", "Note"),
                    ("CANVAS", "Canvas"),
                    ("TODO", "Todo"),
                    ("CODE", "Code"),
                    ("IMAGE", "Image"),
                ],
                default="NOTE",
                max_length=10,
            ),
        ),
    ]
