# Generated by Django 5.2.7 on 2026-07-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entity',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
